# Curator configuration
# https://www.elastic.co/guide/en/elasticsearch/client/curator/current/configfile.html

elasticsearch:
  client:
    hosts: [http://elasticsearch:9200]
  other_settings:
    username: ${ELASTIC_USERNAME}
    password: ${ELASTIC_PASSWORD}

logging:
  loglevel: INFO
  logformat: default
